# core/models.py

from django.db import models
from django.conf import settings

class ReferenceBook(models.Model):
    """
    Базовый класс для всех справочников системы. Содержит общие поля и методы.
    
    Атрибуты:
        name (CharField): Название справочника.
        description (TextField): Описание справочника (необязательное).
        created_at (DateTimeField): Дата и время создания справочника.
        updated_at (DateTimeField): Дата и время последнего обновления справочника.
    """

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # Это абстрактный класс, он не создаёт таблицу в базе данных

    def __str__(self):
        return self.name


class Document(models.Model):
    """
    Базовый класс для всех документов системы.

    Атрибуты:
        document_type (CharField): Тип документа (например, 'Создание', 'Изменение', 'Удаление').
        reference_data (JSONField): Данные, относящиеся к документу.
        user (ForeignKey): Пользователь, который создал или последний раз обновил документ.
        created_at (DateTimeField): Дата и время создания документа.
        updated_at (DateTimeField): Дата и время последнего обновления документа.
        status (CharField): Статус документа (например, 'Черновик', 'На согласовании', 'Утвержден').
    """
    DOCUMENT_TYPES = (
        ('create', 'Создание'),
        ('update', 'Обновление'),
        ('delete', 'Удаление'),
    )

    STATUS_CHOICES = (
        ('draft', 'Черновик'),
        ('in_review', 'На согласовании'),
        ('approved', 'Утвержден'),
        ('rejected', 'Отклонен'),
    )

    document_type = models.CharField(max_length=10, choices=DOCUMENT_TYPES)
    reference_data = models.JSONField()  # Содержит данные, связанные с документом
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='draft')

    class Meta:
        abstract = True

    def __str__(self):
        return f"Document #{self.id} - {self.get_document_type_display()} - {self.get_status_display()}"
    

class Report(models.Model):
    """
    Базовый класс для всех отчетов системы.

    Атрибуты:
        generated_at (DateTimeField): Дата и время генерации отчета.
        generated_by (ForeignKey): Пользователь, который сгенерировал отчет.
        report_data (JSONField): Данные отчета в формате JSON.
    """
    generated_at = models.DateTimeField(auto_now_add=True)
    generated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    report_data = models.JSONField()  # Поле для хранения данных отчета в формате JSON

    class Meta:
        abstract = True

    def __str__(self):
        return f"Report generated by {self.generated_by} on {self.generated_at}"